analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5250627
  brandStrength: 0.741228
  lightness: 0
  brandColors:
    - '#091225'
    - '#45566A'
    - '#25344B'
    - '#EAEAF2'
    - '#8C92A3'
  rhythmicContrast: 0.221178
typography_spectrum: 0.5721997995860875
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9818296
favicon: null
name: Maxime De Campenaere
